version: "3"


services:
  postgresql:
    image: postgres:12-alpine
    hostname: $${POSTGRES_HOST}
    container_name: matemeet-postgresql
    env_file:
      - services/postgresql/.env
    ports:
      - 5432:5432
    volumes:
      - pg-data-matemeet:/var/lib/postgresql/data


  matemeet-api-service:
    image: matemeet-backend
    container_name: django-backend
    user: appuser
    build: services/backend/
    env_file:
      - services/backend/.env
      - services/postgresql/.env
    ports:
      - 8000:8000
    volumes:
      - ./services/backend/service/api:/home/appuser/project/api/
      - ./services/backend/service/apps:/home/appuser/project/apps/
      - ./services/backend/service/libs:/home/appuser/project/libs/
      - ./services/backend/service/tests:/home/appuser/project/tests/
      - ./services/backend/service/static:/home/appuser/project/static/
      - ./services/backend/service/locales:/home/appuser/project/locales/
      - ./services/backend/service/settings:/home/appuser/project/settings/
    depends_on:
      - postgresql
    command: /bin/bash -c "
      ./wait-for.sh $${POSTGRES_HOST}:$${POSTGRES_PORT} &&
      python3 manage.py migrate &&
      python3 manage.py runserver 0.0.0.0:8000"
volumes:
  pg-data-matemeet:
