# Generated by Django 3.0.8 on 2021-05-04 01:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_auto_20210504_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('not started', 'not started'), ('in progress', 'in progress'), ('finished', 'finished')], default='not started', max_length=64),
        ),
        migrations.CreateModel(
            name='EventPhoto',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.ImageField(help_text='Event photo file', upload_to='event/', verbose_name='event_photo')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event photo file',
                'verbose_name_plural': 'Event photo files',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='event_photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profiles', related_query_name='profile', to='apps.EventPhoto'),
        ),
    ]
